name: using environment variables in the workflow
on: workflow_dispatch
env:
  MY_FIRST_ENV: "this is my first environment variable from the workflow level"
  MY_SECOND_ENV: "this is my second environment variable from the workflow level"
  MY_THIRD_ENV: "this is my third environment variable from the workflow level"
jobs:
  job-1:
    env:
      MY_FIRST_ENV: "this is my first environment variable from the job level"
      MY_SECOND_ENV: "this is my second environment variable from the job level"
    runs-on: ubuntu-latest
    steps:
    
      - name: calling my first environment variable
        env:
          MY_FIRST_ENV: "this is my first environment variable from the step level"
          MY_SECOND_ENV: "this is my second environment variable from the step level"
        run: echo "this is my first environment variable $MY_FIRST_ENV"

      - name: calling my second environment variable
        run: echo "this is my second environment variable $MY_SECOND_ENV"

      - name: calling my third environment variable
        run: echo "this is my third environment variable $MY_THIRD_ENV"
