name: First Workflow
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: fist workflow
        run: echo "Hello World"

      - name: second step
        run: echo "hello from second step"

      - name: Third step for multiple run commands
        run: |
        ls -l
        pwd
        touch lucky{1..10}.txt
        ls -l
        echo " hello hi"
