name: IF Condition
on: 
    push:
     branches:
         - main
         - master
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: if branch is master then print this message
        if: github.ref_name == 'master'
        run: |
          echo "This is the master branch"