name: MyFirstWorkflow

on: [workflow_dispatch, push]


jobs:
  job-1:
   runs-on: ubuntu-latest

   steps:
    - name: first step
      run: echo "my first workflow"

    - name: second step
      run: |
        echo "this is my second step"
        whoami
        ls -la
        pwd 

