name: using the uses keyword to call the actions from the marketplace
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: calling the checkout action
        uses: actions/checkout@v7

      - name: calling the setup-java action
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: build the java application
        run: |
         java -version
         echo " THE BRANCH IS >>> ${{ github.ref }}"
         mvn -version
         mvn clean install
     
      - name: Commit files
        run: |
         git config --local user.email "bolisetti33@gmail.com"
         git config --local user.name "Lakshman Bolisetti"
         git commit -a -m "Add changes from github workflow"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          token: ${{ secrets.APPLICATION_TOKEN }}
          branch: ${{ github.ref }}